### ISSUE TITLE
Update README to accomodate changes in data portals

### ISSUE THREAD

**Issue by patcon** [ahmadassaf/OpenData-Checker#16]
It seems that publicdata.eu is now no longer compatible for some reason. I can't seem to find their API endpoint ,so that's likely it. Datahub.io still seems to work though.

If you have time to do a quick confirmation, I'd be happy to update docs to remove mentions of publicdata.eu

**Comment by ahmadassaf** [comment]
thanks for the heads up .. i have just updated the readme
